const division = document.createElement("div");
const header = document.createElement("header");
division.append(header);
const h1 = document.createElement("h1");
h1.innerText = "This is heading";
header.append(h1);
const section = document.createElement("section");
const span = document.createElement("span");
span.innerText = "this is Span";
section.append(span);
division.append(section);
const article = document.createElement("article");
const para = document.createElement("p");
para.innerText = "this is Para";
article.append(para);
division.append(article);
division.setAttribute("style", "background-color:yellow");
header.setAttribute("style", "background-color:red");
document.body.append(division);
